[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-scripts"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api/get_fitness"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
QUEUE_CONNECTION = "sync"

[environments.development.variables]
APP_ENV = "local"
APP_DEBUG = "true"
LOG_LEVEL = "debug"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
QUEUE_CONNECTION = "sync" 